### ISSUE TITLE
Which pointcloud_to_laserscan branch to use? 

### ISSUE THREAD

**Issue by melkonyan** [Roboy/autonomous_driving_src#1]
Description says:

git pull origin lunar-devel
git checkout indigo-devel

Which version is the one we need?

**Comment by melkonyan** [comment]
@christqoh

**Comment by christqoh** [comment]
As stated you need to pull one and switch to the other. Will run into errors otherwise. There’s no master branch to pull that’s why lunar is first. However, for building we need indigo.

**Comment by christqoh** [comment]
Also, if building fails, check the FAQ section of the latest README in `devel`-branch @melkonyan. Will open PR if this solves it for you.
